#!/bin/bash

lyrics_dir=~/tmp/.lyrics

cd $lyrics_dir
IFS=$'\n'
files=$(grep -l 'xml version=' *)
notify-send $(printf "%s\n" "${files[@]}" | cut -d . -f 1)
for file in $files; do
    rm -f $file
done
