#!/bin/bash
# convert seperated snippet files into an integrated one.

if [ $# -lt 2 ]; then
    echo "Usage: $0 [source-files] [target-file]"
    exit 1
fi

for f in ${@:1:$(($#-1))}; do
    sn=${f//.snippet/}
    sn=${sn//./-}
    dest=${@: -1}
    echo "snippet $sn" >> $dest
    cat $f >> $dest
    echo -e '\n' >> $dest
done

vim $dest -c 'g!/^snippet/normal >>'
