#!/usr/bin/bash

fp=~/tmp/.ss_free
urlbase=http://www.ss-link.com

curl -c $fp -d 'email=farseer90718%40gmail.com&redirect=%2Fmy&password=c33367701511b4f6020ec61ded352059' $urlbase/login
password=$(curl -b "$fp" $urlbase/my/free | grep -e '<td>[0-9]\{8\}</td>' | tail -1 | sed 's/[^0-9]//g')

echo -e '\n-----------------------------'
echo 'Password is '$password
echo '-----------------------------'

sudo sed -i $fp -e 's/[0-9]\{8\}/'$password'/g' /etc/shadowsocks/free.json && \
sudo systemctl restart shadowsocks@free.service && \

echo -e '\n-----------------------------\n ss has restarted \n-----------------------------'
