#!/usr/bin/bash

fp=~/tmp/.ss_free
urlbase=http://my.ss-link.com

curl -d "email=farseer90718%40gmail.com&redirect=%2Fmy&password=c33367701511b4f6020ec61ded352059" --dump-header $fp $urlbase/login
cookie=$(cat $fp | grep Set-Cookie | cut -d " " -f 2)

password=$(curl --cookie "$cookie" $urlbase/my/free | grep -e "<td>[0-9]\{8\}</td>" | tail -1 | sed 's/[^0-9]//g')

echo ""
echo "-----------------------------"
echo "Password is "$password
echo "-----------------------------"

sudo sed -i $fp -e 's/[0-9]\{8\}/'$password'/g' /etc/shadowsocks/free.json
sudo systemctl restart shadowsocks@free.service
