#!/bin/bash

raise-or-run "tabbed.tabbed" "tabbed" &
until wmctrl -lx | grep "tabbed.tabbed"; do
    sleep 0.5
done
wmctrl -r :ACTIVE:

if [ "$#" = 0 ]; then
    zathura -e `wmctrl -lx | grep "tabbed.tabbed" | cut -d' ' -f1`
else
    zathura -e `wmctrl -lx | grep "tabbed.tabbed" | cut -d' ' -f1` "$1"
fi
